#ifndef __CODEGEN_TEST_H__
#define __CODEGEN_TEST_H__

// Function declarations for tests
char* test_generate_return_42();
char* test_generate_return_negative();
char* test_generate_return_max_int();
char* test_generate_return_min_int();
char* test_generate_add();
char* test_generate_sub();
char* test_generate_mul();
char* test_generate_div();
char* test_generate_precedence();
char* test_generate_parentheses();
char* test_generate_complex();
char* test_generate_lt_true();
char* test_generate_lt_false();
char* test_generate_eq_true();
char* test_generate_ne_false();
char* test_generate_main_required();
char* test_generate_pointer_example();
char* test_generate_pointer_arithmetic();
char* test_generate_pointer_arithmetic_sub();
char* test_generate_sizeof();
char* test_generate_sizeof_expr();
char* test_generate_array();
char* test_generate_array_subscript();
char* test_generate_array_subscript_reversed();
char* test_generate_global_var();
char* test_generate_global_ptr_var();
char* test_generate_global_array();
char* test_generate_global_array_subscript();
char* test_generate_global_ptr_return_func();
char* test_generate_char_array();
char* test_generate_string_literal();
char* test_generate_struct();
char* test_generate_struct_simple();
char* test_generate_struct_assign();
char* test_generate_char_simple();
char* test_generate_comments();
char* test_generate_sizeof_types();
char* test_generate_logic();
char* test_generate_char_literal();
char* test_generate_arrow();
char* test_generate_typedef();
char* test_generate_enum();
char* test_generate_builtin_const();
char* test_generate_switch();
char* test_generate_switch_distinct_case_values();
char* test_generate_switch_case_after_return_case();
char* test_generate_inc_dec();
char* test_generate_proto_and_init();

#endif
