#ifndef __PARSE_TEST_H__
#define __PARSE_TEST_H__

#include "../src/parse.h"

// Test functions
char* test_new_node_num();
char* test_new_node();
char* test_unary_num();
char* test_unary_plus();
char* test_unary_minus();
char* test_unary_plus_num();
char* test_unary_minus_mul();
char* test_primary_num();
char* test_primary_paren();
char* test_mul_single_num();
char* test_mul_multiply();
char* test_mul_divide();
char* test_mul_chain();
char* test_expr_single_num();
char* test_expr_add();
char* test_expr_subtract();
char* test_expr_add_sub_chain();
char* test_expr_precedence();
char* test_expr_complex_precedence();
char* test_relational_lt();
char* test_relational_le();
char* test_relational_gt();
char* test_relational_ge();
char* test_equality_eq();
char* test_equality_ne();
char* test_expr_combined_precedence();
char* test_new_node_ident();
char* test_new_node_ident_abc();
char* test_primary_ident();
char* test_assign();
char* test_assign_chain();
char* test_stmt();
char* test_stmt_assign();
char* test_stmt_return_num();
char* test_stmt_return_ident();
char* test_stmt_return_expr();
char* test_stmt_if();
char* test_stmt_if_else();
char* test_stmt_if_with_block();
char* test_stmt_if_complex_cond();
char* test_stmt_while();
char* test_stmt_while_complex_cond();
char* test_stmt_for();
char* test_stmt_for_no_init();
char* test_stmt_call();
char* test_stmt_call_with_args();
char* test_program_single_stmt();
char* test_program_multiple_stmts();
char* test_program_assign_stmts();
char* test_function_simple();
char* test_function_multiple_stmts();
char* test_program_single_function();
char* test_program_multiple_functions();
char* test_function_with_block();
char* test_function_with_params();
char* test_function_with_single_param();

#endif
