# Tiny-C Compiler Makefile
TARGET = ./build/llvm7
TARGET2 = ./build/tmp
DEMO ?= ./demo/example02.c

CC = clang
CFLAGS = -Wall -Wextra -O2 -g -std=c99 -Isrc -MMD -MP `llvm-config --cflags`
LDFLAGS = `llvm-config --ldflags --libs --system-libs`

# Directory structure
BUILD_DIR = build
TMP_DIR = tmp
SRC_DIR = src

# Source files
C_SRCS = $(wildcard src/*.c)
C_OBJS = $(patsubst src/%.c,$(BUILD_DIR)/%.o,$(C_SRCS))

# Dependency files (.d files are auto-generated by compiler with -MMD flag)
# Format: build/file.d  contains the dependencies for build/file.o
DEPS = $(C_OBJS:.o=.d)

# Default target
.PHONY: all
all: $(TARGET)

# Include generated dependency files
# The - prefix means "include if exists, don't error if missing"
# Each .d file contains make rules like:
#   build/main.o: src/main.c src/file.h src/generate.h
# So when a header changes, make knows which .o files need rebuilding
-include $(DEPS)

.PHONY: run
run: $(TARGET)
	$(TARGET) $(DEMO)

.PHONY: run2
run2: $(TARGET)
	$(TARGET) $(DEMO) -o tmp.ll
	@echo "Generating .s: $@"
	llc tmp.ll -o tmp.s
	@echo "Linking $(TARGET2)..."
	clang -o $(TARGET2) tmp.s $(LDFLAGS)
	@chmod +x $(TARGET2)
	@$(TARGET2); echo "Exit code: $$?"


.PHONY: test
test:
	$(MAKE) -C test test

.PHONY: clean
clean:
	rm -rf $(BUILD_DIR) $(TMP_DIR) $(TARGET) $(BOOTSTRAP_DIR) $(SELFHOST_DEMO_DIR)
	$(MAKE) -C test clean

.PHONY: format
format:
	clang-format -i $(SRC_DIR)/*.c $(SRC_DIR)/*.h demo/*.c demo/*.h
	$(MAKE) -C test format

# TARGET
$(TARGET): $(BUILD_DIR) $(C_OBJS)
	@echo "Linking $(TARGET)..."
	@echo "C_OBJS: $(C_OBJS)"
	$(CC) $(CFLAGS) -o $(TARGET) $(C_OBJS) $(LDFLAGS)
	@chmod +x $(TARGET)

# Object files with auto-generated dependencies
$(BUILD_DIR)/%.o: $(SRC_DIR)/%.c | $(BUILD_DIR)
	@echo $(CC) $(CFLAGS) -Isrc -c $< -o $@
	$(CC) $(CFLAGS) -Isrc -c $< -o $@

# Directories

$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

$(TMP_DIR):
	mkdir -p $(TMP_DIR)

.PHONY: clean_deps
clean_deps:
	rm -f $(DEPS)

# Self-hosting: compile the compiler with itself
SELFHOST_DIR = selfhost
SELFHOST_BUILD = $(SELFHOST_DIR)/build
SELFHOST_INC = $(SELFHOST_DIR)/include
SELFHOST_TARGET = $(BUILD_DIR)/llvm7_selfhost
SELFHOST_SRCS = stdio.c main.c lex.c parse.c codegen.c file.c variable.c
BOOTSTRAP_DIR = $(SELFHOST_DIR)/bootstrap
BOOTSTRAP_INPUT_DIR = $(BOOTSTRAP_DIR)/input
BOOTSTRAP_TC1_DIR = $(BOOTSTRAP_DIR)/tc1
BOOTSTRAP_TC2_DIR = $(BOOTSTRAP_DIR)/tc2
BOOTSTRAP_CASES = $(SELFHOST_SRCS) $(notdir $(wildcard demo/*.c))
SELFHOST_DEMO_DIR = $(SELFHOST_DIR)/demo_check

.PHONY: selfhost
selfhost: $(TARGET) $(SELFHOST_BUILD)
	@echo "=== Self-hosting: compiling with own compiler ==="
	@for src in $(SELFHOST_SRCS); do \
		echo "  CPP+COMPILE: src/$$src"; \
		clang -E -nostdinc -I$(SELFHOST_INC) -Isrc -P src/$$src `llvm-config --cflags` -o $(SELFHOST_BUILD)/$${src%.c}.i || exit 1; \
		$(TARGET) $(SELFHOST_BUILD)/$${src%.c}.i -o $(SELFHOST_BUILD)/$${src%.c}.ll || exit 1; \
	done
	@echo "  LLVM-LINK..."
	llvm-link $(patsubst %.c,$(SELFHOST_BUILD)/%.ll,$(SELFHOST_SRCS)) -o $(SELFHOST_BUILD)/combined.bc
	@echo "  CLANG LINK..."
	clang $(SELFHOST_BUILD)/combined.bc -o $(SELFHOST_TARGET) $(LDFLAGS) -lc
	@chmod +x $(SELFHOST_TARGET)
	@echo "=== Self-host build complete: $(SELFHOST_TARGET) ==="

.PHONY: selfhost_test
selfhost_test: selfhost
	@echo "=== Verifying selfhost binary ==="
	$(SELFHOST_TARGET) $(DEMO) -o $(SELFHOST_BUILD)/verify.ll
	$(TARGET) $(DEMO) -o $(SELFHOST_BUILD)/original.ll
	@diff $(SELFHOST_BUILD)/original.ll $(SELFHOST_BUILD)/verify.ll && echo "PASS: Output matches" || echo "FAIL: Output differs"

$(SELFHOST_BUILD):
	mkdir -p $(SELFHOST_BUILD)

.PHONY: bootstrap_prepare
bootstrap_prepare:
	@mkdir -p $(BOOTSTRAP_INPUT_DIR) $(BOOTSTRAP_TC1_DIR) $(BOOTSTRAP_TC2_DIR)
	@echo "=== bootstrap: preprocess inputs ==="
	@for src in $(SELFHOST_SRCS); do \
		echo "  preprocess src/$$src"; \
		clang -E -nostdinc -I$(SELFHOST_INC) -Isrc -P src/$$src `llvm-config --cflags` -o $(BOOTSTRAP_INPUT_DIR)/$${src%.c}.i || exit 1; \
	done
	@for src in $(wildcard demo/*.c); do \
		base=$$(basename $$src .c); \
		echo "  preprocess $$src"; \
		clang -E -nostdinc -I$(SELFHOST_INC) -Isrc -P $$src `llvm-config --cflags` -o $(BOOTSTRAP_INPUT_DIR)/$$base.i || exit 1; \
	done

.PHONY: bootstrap_tc1_outputs
bootstrap_tc1_outputs: $(TARGET) bootstrap_prepare
	@echo "=== bootstrap: tc1 outputs ==="
	@for c in $(BOOTSTRAP_CASES); do \
		base=$${c%.c}; \
		echo "  tc1 compile $$base.i"; \
		$(TARGET) $(BOOTSTRAP_INPUT_DIR)/$$base.i -o $(BOOTSTRAP_TC1_DIR)/$$base.ll || exit 1; \
	done

.PHONY: bootstrap_tc2
bootstrap_tc2: selfhost
	@echo "=== bootstrap: tc2 ready ($(SELFHOST_TARGET)) ==="

.PHONY: bootstrap_tc2_outputs
bootstrap_tc2_outputs: bootstrap_tc2 bootstrap_prepare
	@echo "=== bootstrap: tc2 outputs ==="
	@for c in $(BOOTSTRAP_CASES); do \
		base=$${c%.c}; \
		echo "  tc2 compile $$base.i"; \
		$(SELFHOST_TARGET) $(BOOTSTRAP_INPUT_DIR)/$$base.i -o $(BOOTSTRAP_TC2_DIR)/$$base.ll || exit 1; \
	done

.PHONY: bootstrap_compare
bootstrap_compare: bootstrap_tc1_outputs bootstrap_tc2_outputs
	@echo "=== bootstrap: compare tc1 vs tc2 ==="
	@for c in $(BOOTSTRAP_CASES); do \
		base=$${c%.c}; \
		echo "  diff $$base.ll"; \
		diff -u $(BOOTSTRAP_TC1_DIR)/$$base.ll $(BOOTSTRAP_TC2_DIR)/$$base.ll || exit 1; \
	done
	@echo "PASS: tc1 and tc2 outputs are identical on bootstrap cases"

.PHONY: bootstrap_check
bootstrap_check: test bootstrap_compare
	@echo "PASS: tests + bootstrap compare"

.PHONY: selfhost_demo_check
selfhost_demo_check: selfhost
	@echo "=== selfhost demo check ==="
	@mkdir -p $(SELFHOST_DEMO_DIR)/input $(SELFHOST_DEMO_DIR)/ll $(SELFHOST_DEMO_DIR)/bin
	@for src in demo/*.c; do \
		base=$$(basename $$src .c); \
		echo "  preprocess $$src"; \
		clang -E -nostdinc -I$(SELFHOST_INC) -Isrc -P $$src `llvm-config --cflags` -o $(SELFHOST_DEMO_DIR)/input/$$base.i || exit 1; \
		echo "  selfhost compile $$base.i"; \
		$(SELFHOST_TARGET) $(SELFHOST_DEMO_DIR)/input/$$base.i -o $(SELFHOST_DEMO_DIR)/ll/$$base.ll || exit 1; \
		expected=""; \
		case $$base in \
			example01) expected=4 ;; \
			example02) expected=5 ;; \
			example03) expected=42 ;; \
			example04) expected=42 ;; \
			example05) expected=55 ;; \
			example06) expected=55 ;; \
			example07) expected=3 ;; \
			example08) expected=13 ;; \
			example09) expected=4 ;; \
		esac; \
		if [ -n "$$expected" ]; then \
			clang $(SELFHOST_DEMO_DIR)/ll/$$base.ll -o $(SELFHOST_DEMO_DIR)/bin/$$base `llvm-config --ldflags --libs --system-libs` -lc || exit 1; \
			$(SELFHOST_DEMO_DIR)/bin/$$base >/dev/null 2>&1; \
			actual=$$?; \
			if [ "$$actual" -ne "$$expected" ]; then \
				echo "FAIL: $$base expected $$expected got $$actual"; \
				exit 1; \
			fi; \
			echo "  PASS $$base (exit=$$actual)"; \
		else \
			echo "  SKIP $$base (no expected exit check)"; \
		fi; \
	done
	@echo "PASS: all demo sources compiled; checked expected exits for example01..example09"
